version: '3.6'
services:
 elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.0
    volumes:
       - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
       - 9200:9200
 kibana:
    image: docker.elastic.co/kibana/kibana:6.2.0
    depends_on:
      - elasticsearch
    ports:
       - 5601:5601
